/*

 BKG.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Z:\home\andres\gbdk\projects\gb\tetris\tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define bkgWidth 20
#define bkgHeight 18
#define bkgBank 0

extern unsigned char bkg[];

/* End of BKG.H */
